# ----------------------
# <auto-generated>
#    WARNING: this file was generated by an automated tool; manual edits will be lost when it is re-generated.
#
#    The source code below was extracted from `./CSV (PowerShell).rdfe`
#
#    Do not edit this file; instead update the scripts embedded in `./CSV (PowerShell).rdfe`
# </auto-generated>
# ----------------------

$ErrorActionPreference = "Stop"

$computers = Import-Csv "$CustomProperty.CSVPath$"

$connections = @()

ForEach ($computer in $computers) {
    $name = $computer.Name
    $computerName = $computer.ComputerName
    $username = $computer.Username
    $password = $computer.Password

    $connection = New-Object pscustomobject -Property @{
        "Type" = "TerminalConnection";
        "TerminalConnectionType" = "SSH";
        "Name" = $name;
        "ComputerName" = $computerName;
        "Username" = $username;
        "Password" = $password;
    }

    $connections += $connection
}

@{
    Objects = $connections
} |
ConvertTo-Json -Depth 100 |
Write-Host