# ----------------------
# <auto-generated>
#    WARNING: this file was generated by an automated tool; manual edits will be lost when it is re-generated.
#
#    The source code below was extracted from `./Keeper KSM (Python).rdfx`
#
#    Do not edit this file; instead update the scripts embedded in `./Keeper KSM (Python).rdfx`
# </auto-generated>
# ----------------------


"""
Keeper Secrets Manager - Dynamic Credential Script for Royal TS/TSX
Author: Keeper Security
Version: 1.0.0

This script fetches a specific credential from Keeper when a connection
requests it. Returns Username, Password, and KeyFileContent (for SSH keys).
"""

import configparser
import json
import os
import sys
import tempfile
from typing import Any, Dict, List, Optional

# Configuration from Custom Properties
ksm_config_path_macos = r"$CustomProperty.KSMConfigPathmacOS$"
ksm_config_path_windows = r"$CustomProperty.KSMConfigPathWindows$"
item_id = r"$DynamicCredential.EffectiveID$"

# Suppress warnings
os.environ['KSM_CONFIG_SKIP_MODE_WARNING'] = 'TRUE'


def _get_db_default_port(db_type: str) -> str:
    return {"mysql": "3306", "postgres": "5432", "mssql": "1433",
            "oracle": "1521", "mongodb": "27017", "redis": "6379"}.get(db_type, "3306")


def _normalize_db_type(raw: str) -> str:
    t = raw.strip().lower() if raw else ""
    if not t:
        return "mysql"
    if t in ("mysql", "mariadb"):
        return "mysql"
    if t in ("postgresql", "postgres", "pg"):
        return "postgres"
    if t in ("mssql", "sql server", "sqlserver", "microsoft sql server"):
        return "mssql"
    if t in ("oracle", "oracledb"):
        return "oracle"
    if t in ("mongodb", "mongo"):
        return "mongodb"
    if t == "redis":
        return "redis"
    return "mysql"


def _normalize_db_port(port: Any, db_type: str) -> str:
    """Keeper may send 0; omitting Port made Royal TS use $$Port$$ = 0 for psql."""
    default = _get_db_default_port(db_type)
    if port is None:
        return default
    s = str(port).strip()
    if not s or s == "0":
        return default
    try:
        n = int(s)
        if n <= 0 or n > 65535:
            return default
    except ValueError:
        return default
    return str(n)


class RoyalUtils:
    """Utility class for Royal TS/TSX operations."""
    
    @staticmethod
    def is_macOS() -> bool:
        """Check if running on macOS."""
        return sys.platform.lower().startswith("darwin")
    
    @staticmethod
    def exit_with_error(message: str, exception: Optional[Exception] = None,
                        hint: Optional[str] = None) -> None:
        """Print error message and exit. Never logs credentials or sensitive data."""
        err_type = type(exception).__name__ if exception else "Error"
        out = f"{message}: {err_type}"
        if hint:
            out += f" - {hint}"
        sys.stderr.write(out + "\n")
        sys.exit(1)
    
    @staticmethod
    def to_json(obj: Any, pretty: bool = False) -> str:
        """Convert object to JSON string."""
        return json.dumps(obj, indent=4) if pretty else json.dumps(obj)


def _create_ksm_storage(
    config_path: str,
    profile_name: str = "_default",
    temp_paths: Optional[List[str]] = None,
):
    """Create KSM storage from .ini, .json, or .base64 config file."""
    import base64

    from keeper_secrets_manager_core.configkeys import ConfigKeys
    from keeper_secrets_manager_core.storage import FileKeyValueStorage, InMemoryKeyValueStorage

    ext = os.path.splitext(config_path)[1].lower()

    if ext == ".json":
        return FileKeyValueStorage(config_path)
    if ext == ".base64":
        with open(config_path, encoding="utf-8") as f:
            decoded = base64.b64decode(f.read().strip()).decode("utf-8")
        fd, tmp_path = tempfile.mkstemp(suffix=".json", prefix="ksm_", text=True)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as tf:
                tf.write(decoded)
            try:
                os.chmod(tmp_path, 0o600)
            except OSError:
                pass
            if temp_paths is not None:
                temp_paths.append(tmp_path)
            return FileKeyValueStorage(tmp_path)
        except Exception:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass
            raise
    # .ini or default
    config = configparser.ConfigParser(allow_no_value=True)
    config.read(config_path)
    if profile_name not in config.sections():
        raise ValueError(f"Profile '{profile_name}' not found in {config_path}")
    profile = config[profile_name]
    storage = InMemoryKeyValueStorage()
    key_mapping = {
        "clientid": ConfigKeys.KEY_CLIENT_ID,
        "privatekey": ConfigKeys.KEY_PRIVATE_KEY,
        "appkey": ConfigKeys.KEY_APP_KEY,
        "hostname": ConfigKeys.KEY_HOSTNAME,
        "appownerpublickey": ConfigKeys.KEY_OWNER_PUBLIC_KEY,
        "serverpublickeyid": ConfigKeys.KEY_SERVER_PUBLIC_KEY_ID,
    }
    for ini_key, sdk_key in key_mapping.items():
        if ini_key in profile and profile[ini_key]:
            storage.set(sdk_key, profile[ini_key])
    return storage


class KeeperKSM:
    """Keeper Secrets Manager client. Supports .ini, .json, and .base64 config formats."""

    def __init__(
        self,
        config_path: str,
        profile_name: str = "_default",
        temp_paths: Optional[List[str]] = None,
    ):
        """
        Initialize KSM client. Config format is auto-detected from file extension.

        Args:
            config_path: Path to config file (.ini, .json, or .base64)
            profile_name: Profile section name for .ini files only
            temp_paths: If set, decoded .base64 temp paths are appended for cleanup.
        """
        try:
            from keeper_secrets_manager_core import SecretsManager
        except ImportError:
            raise ImportError(
                "keeper-secrets-manager-core is not installed. "
                "Run: pip install keeper-secrets-manager-core"
            )
        if not config_path or config_path.startswith("$"):
            raise ValueError("KSM Config Path is not configured. Set it in Custom Properties.")
        if not os.path.exists(config_path):
            raise FileNotFoundError(f"KSM config file not found: {config_path}")
        storage = _create_ksm_storage(config_path, profile_name, temp_paths=temp_paths)
        self.client = SecretsManager(config=storage)

    def get_credential(self, uid: str) -> Dict[str, Any]:
        """
        Fetch a specific credential by UID.
        
        Handles multiple Keeper record types:
        - Server record: login + password fields + host
        - SSH Key record: login + keyPair (nested privateKey) + password (labeled as passphrase) + host
        - Database record: login + password + host
        - Login record: login + password fields
        
        Args:
            uid: The Keeper record UID
            
        Returns:
            Dictionary with Username, Password, URI, Port, and optionally KeyFileContent/KeyFilePassphrase
        """
        secrets = self.client.get_secrets([uid])
        
        if not secrets:
            return {"Error": f"Secret {uid} not found"}
        
        secret = secrets[0]
        result = {}
        record_type = secret.type
        
        # Extract username from 'login' field (common across record types)
        try:
            login = secret.field("login", single=True)
            if login:
                result["Username"] = login
        except (TypeError, ValueError, AttributeError, LookupError):
            pass

        # Extract password field (used differently by record types)
        password = None
        try:
            password = secret.field("password", single=True)
        except (TypeError, ValueError, AttributeError, LookupError):
            pass

        # Extract host and port (for $URI$ and $Port$ tokens)
        try:
            host_data = secret.field("host")
            if host_data and len(host_data) > 0:
                if isinstance(host_data[0], dict):
                    host_name = host_data[0].get("hostName")
                    port = host_data[0].get("port")
                    if host_name:
                        result["URI"] = host_name
                    if record_type == "databaseCredentials":
                        try:
                            db_raw = secret.field("text", single=True)
                            db_t = _normalize_db_type(db_raw or "")
                        except (TypeError, ValueError, AttributeError, LookupError):
                            db_t = "mysql"
                        result["Port"] = _normalize_db_port(port, db_t)
                    elif port:
                        result["Port"] = port
        except (TypeError, ValueError, AttributeError, LookupError):
            pass

        # Extract private key - check keyPair first (SSH Key records), then standalone privateKey
        private_key = None
        try:
            # SSH Key records store private key inside keyPair object
            key_pair = secret.field("keyPair", single=True)
            if key_pair and isinstance(key_pair, dict):
                private_key = key_pair.get("privateKey")
        except (TypeError, ValueError, AttributeError, LookupError):
            pass

        if not private_key:
            # Fallback: try standalone privateKey field
            try:
                private_key = secret.field("privateKey", single=True)
            except (TypeError, ValueError, AttributeError, LookupError):
                pass

        # Handle based on record type and available fields
        if record_type == "sshKeys":
            # SSH Key record: password field is labeled "passphrase" (key passphrase)
            if private_key:
                result["KeyFileContent"] = private_key
                if password:
                    # password field in sshKeys is the key's passphrase
                    result["KeyFilePassphrase"] = password
            elif password:
                # No private key, password is SSH login password
                result["Password"] = password
        else:
            # Server/Login/other records: password is the login password
            if password:
                result["Password"] = password
            if private_key:
                result["KeyFileContent"] = private_key
        
        return result


class Coordinator:
    """Coordinates the credential fetching process."""
    
    def __init__(self, config_path_windows: str, config_path_macos: str):
        """Initialize with platform-specific config paths."""
        self.config_path = config_path_macos if RoyalUtils.is_macOS() else config_path_windows
    
    def get_credential(self, credential_id: str) -> None:
        """
        Fetch and output a specific credential.
        
        Args:
            credential_id: The credential ID (keeper://UID format)
        """
        # Extract UID from keeper://UID format
        if credential_id.startswith("keeper://"):
            uid = credential_id[9:]
        else:
            uid = credential_id

        temp_paths: List[str] = []
        try:
            ksm = KeeperKSM(self.config_path, temp_paths=temp_paths)
            credential = ksm.get_credential(uid)
            print(RoyalUtils.to_json(credential, True))
        except Exception as e:
            RoyalUtils.exit_with_error("Error fetching credential", e)
        finally:
            for p in temp_paths:
                try:
                    os.unlink(p)
                except OSError:
                    pass


# Main execution
coordinator = Coordinator(ksm_config_path_windows, ksm_config_path_macos)
coordinator.get_credential(item_id)
